### PR TITLE
Adds parameter disableClick to allow for typing in the datetimefield

### PR DESCRIPTION
**Pull request by EmielH**
I added a new parameter disableClick that allows the user to type in the datefield, instead of opening the datetimepicker once the field gets focus. This is best used in combination with a button that opens the datetimepicker. This mimics the way the md-datepicker works by default. See https://material.angularjs.org/latest/demo/datepicker

The input the user types in the field needs to conform to the format. I added a parser that converts the user input to a Date object. To prevent strange behaviour when parsing datetimes while the user is typing, I added a debounce to the input field. If the datetime isn't valid, the previously set datetime is kept.

The diff for the second half is a bit messy. The only thing I did is add `if (!scope.disableClick)` around the handler for onFocus and increase the indentation.

### CODE REVIEW

**Comment by hexadecy** [comment]
I'm just not sure about the parameter name.
autoShowDialog : true (default)

**Comment by EmielH** [comment]
That's probably a better name. Md-datepicker uses openOnFocus which could also be a good choice.

I've also been thinking about the debounce: maybe it's now impossible for the user of the component to specify a different debounce himself since I've hardcoded 500 ms. I haven't tested this yet, though.

**Comment by hexadecy** [comment]
- [x] Add a demo
- [x] Change parameter name
~~Make debounce configurable~~

**Review by hexadecy — COMMENTED** [review]
good job

**Comment by hexadecy** [comment]
I think the debounce is fine

**Comment by EmielH** [comment]
Awesome. Thanks!

**Comment by hexadecy** [comment]
https://github.com/beenote/angular-material-datetimepicker/tree/v1.6.7

**Pull request merged**
