### PR TITLE
Does not update ngModel states correctly

### PR DESCRIPTION
**Pull request by tw1nk**
I noticed that this library does not update the form controllers $dirty state correctly.

This change fixes that.

### CODE REVIEW

**Comment by hexadecy** [comment]
Do we have a concrete test case? Any possible side effect?

**Comment by Letsan** [comment]
For some reason this update has broken an app I had. Seems that with this change, choosing and confirming a date now sets the ng-model to a Date instance, even if the model was a moment() originally.

For me, reverting to 1.18.1 fixed our issues. Might need some more testing or maybe the ng-model change is the intended behaviour?

**Comment by hexadecy** [comment]
Ok 1.18.2 is now deprecated. I don't know what this PR fix anyway.

**Comment by Letsan** [comment]
Thanks! I haven't tested it thoroughly but 1.18.1 worked fine setting forms as dirty as far as I recall. Not sure what the change did on this PR.

**Pull request merged**
